version: '3'
services:
  web:
      container_name: php7.3_web
      build: ./nginx
      ports:
          - "8080:80"
      depends_on:
          - php
  php:
      container_name: php7.3_php
      build: ./php
      volumes:
          - ./app:/app