version: '3'
services:
  web:
      container_name: fuelphp1.8.0_php5.6_web
      build: ./nginx
      ports:
          - "8080:80"
      depends_on:
          - php
  php:
      container_name: fuelphp1.8.0_php5.6_php
      build: ./php
      volumes:
          - ./app:/app
  blackfire:
    container_name: fuelphp1.8.0_php5.6_blackfire
    env_file: .env
    image: blackfire/blackfire
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN
      - BLACKFIRE_CLIENT_ID
      - BLACKFIRE_CLIENT_TOKEN